name: Deploy Spring Boot to EC2

on:
  push:
    branches: [main] # ou outra branch de produção

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Build com Maven
        run: mvn clean package -DskipTests
      - name: Testar conexão SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
              host: ${{ secrets.EC2_HOST }}
              username: ${{ secrets.EC2_USER }}
              key: ${{ secrets.EC2_SSH_KEY }}
              script: |
                echo "Usuário: $(whoami)"
                ls -la /home/ec2-user/deploy
                java -version


      - name: Copiar arquivo para EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: target/api-0.0.1-SNAPSHOT.jar
          target: /home/ec2-user/deploy/
          strip_components: 1
      - name: Verificar arquivos na EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Arquivos dentro de /home/ec2-user/deploy:"
            ls -lh /home/ec2-user/deploy


      - name: SSH na EC2 e reiniciar aplicação com systemd
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Reiniciando a aplicação com systemd"
            sudo systemctl restart springboot-api
            echo "Esperando o app iniciar..."
            sleep 5
            echo "Últimas linhas do log:"
            sudo journalctl -u springboot-api -n 20

            
      - name: Verificar log da aplicação
        uses: appleboy/ssh-action@v1.0.0
        with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USER }}
            key: ${{ secrets.EC2_SSH_KEY }}
            script: |
              

              echo "Últimas linhas do app.log:"
              tail -n 30 /home/ec2-user/deploy/app.log



          
